{"frames":[{"func":"modelplot(list(model1 = mylm1, model2 = mylm2, model3 = mylm3), \n    vcov = \"robust\")","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"modelsummary(output = \"dataframe\", models = models, fmt = NULL, \n    estimate = estimate, statistic = NULL, conf_level = conf_level, \n    coef_map = coef_map, coef_omit = coef_omit, coef_rename = coef_rename, \n    gof_omit = \".*\", vcov = vcov, exponentiate = exponentiate,  ...","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0},{"func":"sanitize_models(models, ...)","file":"","line_number":0,"end_line_number":0,"character_number":0,"end_character_number":0}],"message":"Error in sanitize_models(models, ...) : object 'mylm2' not found\n"}